### ISSUE TITLE
how to add custom class for active state of a toolbar button?

### ISSUE THREAD

**Issue by Vishal0203** [sstur/react-rte#162]
Is there a way I can add a custom style or class for `active` state of a toolbar button?

**Comment by zbrox** [comment]
That would be a great addition, as well as being able to add text labels to buttons. For now you can use some CSS to style them. Give each button a custom class name using toolbarConfig. I use SCSS usually, like this:

```scss
.bold-button {
    &[class*='isActive'] {
        span {
            background-image: url('/images/bold-button-active.png');
        }
    }

    span {
        background-image: url('/images/bold-button.png');
    }
}
```

or with plain CSS

```css
.bold-button[class*='isActive'] span {
    background-image: url('/images/bold-button-active.png');
}

.bold-button span {
    background-image: url('/images/bold-button.png');
}
```
